sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t habensimanjuntak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true habensimanjuntak/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-211123577914"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
