sudo: required
services:
  - docker

before_install:
  - docker build -t habensimanjuntak/docker-react -f Dockerfile.dev .

script:
  - docker run habensimanjuntak/docker-react npm run test -- --coverage